{{- range $name, $spec := .Values.specs }}
{{- if ne $spec.enabled false }}
---
{{- if and $spec.serviceAccount $spec.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blueprint.serviceAccountName" (dict "root" $ "name" $name "spec" $spec) }}
  labels:
    {{- include "blueprint.labels" (dict "root" $ "name" $name "spec" $spec) | nindent 4 }}
  {{- with $spec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $spec.serviceAccount.automount | default true }}
{{- end }}
{{- end }}
{{- end }}